# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.box_check_update = false
  config.ssh.private_key_path = File.expand_path('~/.vagrant.d/insecure_private_key')
  config.vm.define "lb" do |lb|
    lb.vm.network "private_network", ip: "192.168.33.11"
    lb.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "512"
    end
  end
  config.vm.define "web1" do |web1|
    web1.vm.network "private_network", ip: "192.168.33.21"
    web1.vm.provider "virtualbox" do |vb|
      vb.gui = true
      vb.memory = "512"
    end
  end
  config.vm.define "web2" do |web2|
    web2.vm.network "private_network", ip: "192.168.33.22"
    web2.vm.provider "virtualbox" do |vb|
      vb.gui = true
      vb.memory = "512"
    end
  end
  config.vm.define "db1" do |db1|
    db1.vm.network "private_network", ip: "192.168.33.31"
    db1.vm.provider "virtualbox" do |vb|
      vb.gui = true
      vb.memory = "512"
    end
  end
end
