# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"
    config.vm.box_check_update = false
    config.ssh.insert_key = false
    config.ssh.private_key_path = File.expand_path('~/.vagrant.d/insecure_private_key')
    config.vm.define "web" do |web|
      web.vm.network "private_network", ip: "192.168.33.11"
      web.vm.hostname = "wordpress"
      web.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.memory = "512"
      end
    end
    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "wordpress.yml"
    end
  end
  